### ISSUE TITLE
Can't build, missing signing key

### ISSUE THREAD

**Issue by mkarg** [jze/ods-reader#2]
Currently a normal build (`mvn verify`) fails as the build wants to sign the artifact. This makes no sense for local-only builds. Signing should only happen when actually deploying to a repository.

**Comment by jze** [comment]
Thanks for the hint. Apparently I have to configure Maven so that signing is only executed during a deployment. 

`mvn package` seems to work. Maybe that helps temporarily.

**Comment by mkarg** [comment]
A typical Maven-like solution would be to move the signing into a Maven Profile (so you activate it **manually** using `mvn -P` *or* to bind the signing execution to the `deploy` Phase explicitly, so it runs at `mvn deploy` but not at `mvn verify`. 😃
